package ar.org.centro8.curso.java.entities;
// Generated Apr 9, 2018 3:47:18 PM by Hibernate Tools 4.3.1



/**
 * Alumnos generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private int edad;
     private int idCurso;

    public Alumno() {
    }

    public Alumno(String nombre, String apellido, int edad, int idCurso) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.idCurso = idCurso;
    }

    public Alumno(Integer id, String nombre, String apellido, int edad, int idCurso) {
        this.id = id;
        this.nombre = nombre;
        this.apellido = apellido;
        this.edad = edad;
        this.idCurso = idCurso;
    }

    @Override
    public String toString() {
        return "Alumnos{" + "id=" + id + ", nombre=" + nombre + ", apellido=" + apellido + ", edad=" + edad + ", idCurso=" + idCurso + '}';
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }




}


